version: '3.1'

services:
  beer-backend:
    image: remerick/beer-hub:1.0.0
    container_name: beer-hub-app
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

  beer-frontend:
    build:
      context: ../../FrontEnd/BeerHubApp
    container_name: beer-frontend-app
    ports:
      - "80:80"
    depends_on:
      - beer-backend

  db:
    image: postgres:14.3
    container_name: postgres-container
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}

volumes:
  postgres-db:
    external: false
